package com.github.salamonpavel.zio.utils

import com.github.salamonpavel.zio.exceptions.ParseError
import zio.{ULayer, ZIO, ZLayer}
import zio.http.QueryParams

// 1. Service definition
trait QueryParamsParser {
  def parseRequiredString(queryParams: QueryParams, param: String): ZIO[Any, ParseError, String]
}

// 5. Accessor methods (can be autogenerated with available macros)
object QueryParamsParser {
  def parseRequiredString(queryParams: QueryParams, param: String): ZIO[QueryParamsParser, ParseError, String] = {
    ZIO.serviceWithZIO[QueryParamsParser](_.parseRequiredString(queryParams, param))
  }
}

// 2. Service implementation
class QueryParamsParserImpl extends QueryParamsParser {
  override def parseRequiredString(queryParams: QueryParams, param: String): ZIO[Any, ParseError, String] = {
    ZIO.fromOption(queryParams.get(param)).foldZIO(
      _ => ZIO.fail(ParseError(s"Required parameter not provided: $param")),
      chunk => ZIO.succeed(chunk.asString)
    )
  }
}

// 4. Zlayer constructor
object QueryParamsParserImpl {
  val live: ULayer[QueryParamsParser] = ZLayer.succeed(new QueryParamsParserImpl)
}
