package com.github.salamonpavel.zio.service

import com.github.salamonpavel.zio.model.Actor
import zio.{ZIO, ZLayer}

// 1. Service definition
trait ActorsService {
  def findActorById(id: Int): ZIO[Any, Throwable, Option[Actor]]
}

// 5. Accessor methods (can be autogenerated with available macros)
object ActorsService {
  def findActorById(id: Int): ZIO[ActorsService, Throwable, Option[Actor]] = {
    ZIO.serviceWithZIO[ActorsService](_.findActorById(id))
  }
}

// 2. Service implementation, 3. dependencies passed via constructor
class ActorsServiceImpl(actorsRepository: ActorsRepository) extends ActorsService {
  override def findActorById(id: Int): ZIO[Any, Throwable, Option[Actor]] = {
    for {
      actor <- actorsRepository.getActorById(id)
    } yield actor
  }
}

// 4. ZLayer constructor
object ActorsServiceImpl {
  val live: ZLayer[ActorsRepository, Nothing, ActorsService] =
    ZLayer {
      for {
        actorsRepository <- ZIO.service[ActorsRepository]
      } yield new ActorsServiceImpl(actorsRepository)
    }
}