name: Run Tests

on: 
  workflow_dispatch:
    branches:
      - feature/only-here

jobs:
  test:
    runs-on: ubuntu-latest

    # https://docs.github.com/en/actions/using-containerized-services/about-service-containers
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5433:5432 # default postgres port on localhost is 5432, so we map to 5433 in order to avoid conflicts

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Scala and sbt
        uses: olafurpg/setup-scala@v10

      - name: Run database migrations
        run: sbt flywayMigrate

      - name: Run tests
        run: sbt test
